[package]
name    = "pyinit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap      = { version = "4.0", features = ["derive"] }
dialoguer = "0.10"
chrono    = "0.4"
askama    = "0.12"
thiserror = "1"
reqwest   = { version = "0.11", features = ["blocking"] }