[package]
name = "pyinit"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
dialoguer = "0.10"
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking"] }
chrono = "0.4"