name: Build and Release pyinit

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            file_extension: ""
          - target: x86_64-apple-darwin
            file_extension: ""
          - target: x86_64-pc-windows-gnu
            file_extension: ".exe"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for Windows cross-compilation
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get install mingw-w64

      - name: Install Zig for macOS cross-compilation
        if: matrix.target == 'x86_64-apple-darwin'
        run: sudo apt-get install zig

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal

      - name: Build the binary
        run: |
          if [[ "${{ matrix.target }}" == "x86_64-apple-darwin" ]]; then
            zig cc -target x86_64-macos -o target/${{ matrix.target }}/release/pyinit target/${{ matrix.target }}/release/pyinit
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Create compressed archive
        run: |
          zip pyinit-${{ matrix.target }}-${{ github.ref_name }} target/${{ matrix.target }}/release/pyinit${{ matrix.file_extension }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pyinit-${{ matrix.target }}-${{ github.ref_name }}
          path: pyinit-${{ matrix.target }}-${{ github.ref_name }}.zip

  release:
    name: Release pyinit binaries
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pyinit-x86_64-unknown-linux-gnu-*.zip
            pyinit-x86_64-apple-darwin-*.zip
            pyinit-x86_64-pc-windows-gnu-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
