name: Build and Release pyinit CLI

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            file_extension: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            file_extension: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            file_extension: ".exe"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build the CLI
        run: cargo build --release --target ${{ matrix.target }}

      - name: Set executable permissions (Linux/macOS)
        if: ${{ matrix.os != 'windows-latest' }}
        run: chmod +x target/${{ matrix.target }}/release/pyinit

      - name: Archive the build output (Linux/macOS)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          mkdir -p dist
          zip -j dist/pyinit-${{ matrix.os }}-${{ github.ref_name }}.zip target/${{ matrix.target }}/release/pyinit

      - name: Archive the build output (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist
          Compress-Archive -Path "target\${{ matrix.target }}\release\pyinit${{ matrix.file_extension }}" -DestinationPath "dist\pyinit-${{ matrix.os }}-${{ github.ref_name }}.zip"

      - name: Upload build artifacts as release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
